FROM maven:3.9-eclipse-temurin-21 AS builder

WORKDIR /backend
COPY pom.xml .
# Téléchargement des dépendances en cache séparé
RUN mvn dependency:go-offline -B

COPY src ./src
RUN mvn package -DskipTests -B

# Image de runtime allégée
FROM eclipse-temurin:21-jre-alpine


WORKDIR /app
COPY --from=builder /backend/target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]