name: Backend CI

on:
  push:
    branches:
      - DEV
    paths:
      - 'Applications/Backend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'Applications/Backend/**'

env:
  AWS_REGION: eu-west-3
  ECR_REPOSITORY: infoline-api
  EKS_CLUSTER: infoline-cluster

jobs:
  test:
    name: tests
    runs-on: ubuntu-latest

    steps:
      - name: Validation du code
        uses: actions/checkout@v5

      - name: Setup Java 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build et tests Maven
        run: mvn clean verify -B
        working-directory: Applications/Backend/

      - name: Publication des résultats de tests
        uses: actions/upload-artifact@v5
        with:
          name: test-results
          path: Applications/Backend/target/surefire-reports/
          