name: Terraform CI

on:
  push:
    branches: 
      - AWS
  pull_request:
    branches: 
      - main

env:
  TF_VERSION: "1.15.6"

jobs:
  check:
    name: "Terraform Check"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate
